language: php
php:
  - master
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.2
      dist: precise
env: CC=clang
before_script:
  - ./travis/compile.sh
script:
  - exit 0