language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - 5.2
env: CC=gcc
matrix:
  allow_failures:
    - php: nightly
  include:
    - php: 5.4
      env: CC=clang
    - php: 5.5
      env: CC=clang
    - php: 5.6
      env: CC=clang
    - php: 7.0
      env: CC=clang
    - php: 7.1
      env: CC=clang
    - php: 7.2
      env: CC=clang
addons:
  apt:
    packages: clang
